version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx
    # restart: on-failure
    ports:
      - 443:443
    depends_on:
      - wordpress
    volumes:
      - wordpress_vol:/var/www/wordpress
    networks:
      - inception

  mariadb:
    container_name: mariadb 
    image: mariadb
    build: ./requirements/mariadb
    # restart: on-failure
    volumes:
      - mariadb_vol:/var/lib/mysql
    networks:
      - inception
    env_file: 
      - ".env"

  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress/
      # restart: on-failure
    depends_on:
      - mariadb
    volumes:
      - wordpress_vol:/var/www/wordpress
    networks:
      - inception
    env_file:
      - ".env"

networks:
  inception:
    driver: bridge

volumes:
  mariadb_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/jose/data/mariadb_vol
      o: bind
  wordpress_vol:
    driver: local
    driver_opts:
      type: none
      device: /home/jose/data/wordpress_vol
      o: bind
